services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      auth-service:
        condition: service_healthy
      mqtt-service:
        condition: service_healthy
    environment:
      - NODE_ENV=production

  auth-service:
    build: ./services/auth-service
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      retries: 3

  mqtt-service:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      - MQTT_ALLOW_ANONYMOUS=true
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "localhost", "-t", "test"]
      interval: 10s
      retries: 3

  database-service:
    build: ./services/database-service
    ports:
      - "5555:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
